describe('ServiceFlow demo workflow', () => {
  it('moves a customer request through admin and technician approval', () => {
    cy.visit('/')
    cy.contains('button', 'Try Demo').click()
    cy.contains('Good work starts with clarity.')
    cy.get('header select').select('CUSTOMER')
    cy.contains('New request').click()
    cy.get('input[name="title"]').type('Cypress workflow visit')
    cy.get('input[name="address"]').type('Kadikoy, Istanbul')
    cy.get('textarea[name="description"]').type('End-to-end demonstration request.')
    cy.contains('button', 'Submit for review').click()
    cy.contains('NEW')
    cy.get('header select').select('ADMIN')
    cy.contains('Service requests').click()
    cy.contains('Cypress workflow visit').click()
    cy.contains('button', 'Approve for technicians').click()
    cy.contains('REVIEWED')
    cy.get('header select').select('TECHNICIAN')
    cy.contains('Cypress workflow visit').click()
    cy.get('input[type="datetime-local"]').clear().type(new Date(Date.now() + 86400000).toISOString().slice(0, 16))
    cy.contains('button', 'Accept and schedule').click()
    cy.contains('SCHEDULED')
    cy.contains('button', 'Waiting for appointment').should('be.disabled')
    cy.get('header select').select('ADMIN')
    cy.contains('Good work starts with clarity.')
  })
})
