describe('ServiceFlow demo workflow', () => {
  it('moves a request from quotation through technician completion', () => {
    cy.visit('/')
    cy.contains('button', 'Try Demo').click()
    cy.contains('Good work starts with clarity.')
    cy.contains('Customers').click()
    cy.contains('Add customer').click()
    cy.get('input[name="name"]').type('Demo Visitor')
    cy.get('input[name="company"]').type('Demo Services')
    cy.get('input[name="email"]').type('visitor@example.com')
    cy.get('input[name="phone"]').type('+90 555 000 0000')
    cy.get('input[name="address"]').type('Istanbul')
    cy.contains('button', 'Create customer').click()
    cy.contains('Demo Visitor')
    cy.contains('Service requests').click()
    cy.contains('New request').click()
    cy.get('input[name="title"]').type('Cypress workflow visit')
    cy.get('select[name="customerId"]').select('Mert Yilmaz — Northstar Coffee')
    cy.get('input[name="address"]').type('Kadikoy, Istanbul')
    cy.get('textarea[name="description"]').type('End-to-end demonstration request.')
    cy.contains('button', 'Create request').click()
    cy.contains('Create quote').click()
    cy.get('input[name="amount"]').type('2750')
    cy.get('textarea[name="description"]').type('Inspection, parts, and service visit.')
    cy.contains('button', 'Save draft').click()
    cy.contains('button', 'Send quote').click()
    cy.get('header select').select('CUSTOMER')
    cy.contains('Quotations').click()
    cy.contains('Cypress workflow visit').click()
    cy.contains('button', 'Approve').click()
    cy.get('header select').select('ADMIN')
    cy.contains('Quotations').click()
    cy.contains('Cypress workflow visit').click()
    cy.contains('button', 'Create work order').click()
    cy.get('input[name="title"]').type('Complete Cypress workflow visit')
    cy.get('select[name="assignedUserId"]').select('Emre Tekin')
    cy.get('textarea[name="description"]').type('Complete the approved scope and record the result.')
    cy.contains('button', 'Create work order').click()
    cy.get('header select').select('TECHNICIAN')
    cy.contains('Complete Cypress workflow visit').click()
    cy.contains('button', 'Start work').click()
    cy.contains('button', 'Complete work').click()
    cy.contains('COMPLETED')
    cy.get('header select').select('ADMIN')
    cy.contains('Good work starts with clarity.')
  })
})
